### PR TITLE
Move server.conf into repository storage

### PR DESCRIPTION
**Pull request by Thalhammer**
This allows modifying the server config to allow for customization (like enabling anonymous access or asking for user ids).
This prevents having to modify the container to do so, which makes deployment and potential updates a lot easier.

### CODE REVIEW

**Comment by 0xf15h** [comment]
That's a great idea! I want to test it before merging but I'm busy at the moment. I'll get to it as soon as possible in the next few days. Thanks @Thalhammer for your contribution and patience.

**Comment by 0xf15h** [comment]
@Thalhammer I do not understand how a user could access the server.conf file from the /srv/repositories directory. Could you please explain?

**Comment by Thalhammer** [comment]
@0xf15h You can access files in a docker volume as follows:
https://stackoverflow.com/a/49191563
Or by spawing a shell inside the ghidra container.

The important difference however is that if you use a named volume for the repositories (which you obviously want to do) the config file will survive if the container is recreated (e.g. to upgrade ghidra or because of some devops cycle). So its not about easier access but about persistence.

**Comment by 0xf15h** [comment]
Thanks for your contribution @Thalhammer!

**Pull request merged**
